In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [2]:
df=pd.read_csv("iris.data",header=None)
df.iloc[:,4]=df.iloc[:,4].map({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})
df

0    1    2    3  4
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
5    5.4  3.9  1.7  0.4  1
6    4.6  3.4  1.4  0.3  1
7    5.0  3.4  1.5  0.2  1
8    4.4  2.9  1.4  0.2  1
9    4.9  3.1  1.5  0.1  1
10   5.4  3.7  1.5  0.2  1
11   4.8  3.4  1.6  0.2  1
12   4.8  3.0  1.4  0.1  1
13   4.3  3.0  1.1  0.1  1
14   5.8  4.0  1.2  0.2  1
15   5.7  4.4  1.5  0.4  1
16   5.4  3.9  1.3  0.4  1
17   5.1  3.5  1.4  0.3  1
18   5.7  3.8  1.7  0.3  1
19   5.1  3.8  1.5  0.3  1
20   5.4  3.4  1.7  0.2  1
21   5.1  3.7  1.5  0.4  1
22   4.6  3.6  1.0  0.2  1
23   5.1  3.3  1.7  0.5  1
24   4.8  3.4  1.9  0.2  1
25   5.0  3.0  1.6  0.2  1
26   5.0  3.4  1.6  0.4  1
27   5.2  3.5  1.5  0.2  1
28   5.2  3.4  1.4  0.2  1
29   4.7  3.2  1.6  0.2  1
..   ...  ...  ...  ... ..
120  6.9  3.2  5.7  2.3  3
121  5.6  2.8  4.9  2.0  3
122  7.7  2.8  6.7  2.0  3
123  6.3  2.7  4.9  1.8  3
124  6.7  3.3  5.7  2.1  3
125  7.2  3.2  6.0  1.8  3
126  6.2  2.8  4.8  1.8  3
127  6.1  3.0  4.9  1.8  3
128  6.4  2.8  5.6  2.1  3
129  7.2  3.0  5.8  1.6  3
130  7.4  2.8  6.1  1.9  3
131  7.9  3.8  6.4  2.0  3
132  6.4  2.8  5.6  2.2  3
133  6.3  2.8  5.1  1.5  3
134  6.1  2.6  5.6  1.4  3
135  7.7  3.0  6.1  2.3  3
136  6.3  3.4  5.6  2.4  3
137  6.4  3.1  5.5  1.8  3
138  6.0  3.0  4.8  1.8  3
139  6.9  3.1  5.4  2.1  3
140  6.7  3.1  5.6  2.4  3
141  6.9  3.1  5.1  2.3  3
142  5.8  2.7  5.1  1.9  3
143  6.8  3.2  5.9  2.3  3
144  6.7  3.3  5.7  2.5  3
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [3]:
d1=df.iloc[:,:2]
d1

0    1
0    5.1  3.5
1    4.9  3.0
2    4.7  3.2
3    4.6  3.1
4    5.0  3.6
5    5.4  3.9
6    4.6  3.4
7    5.0  3.4
8    4.4  2.9
9    4.9  3.1
10   5.4  3.7
11   4.8  3.4
12   4.8  3.0
13   4.3  3.0
14   5.8  4.0
15   5.7  4.4
16   5.4  3.9
17   5.1  3.5
18   5.7  3.8
19   5.1  3.8
20   5.4  3.4
21   5.1  3.7
22   4.6  3.6
23   5.1  3.3
24   4.8  3.4
25   5.0  3.0
26   5.0  3.4
27   5.2  3.5
28   5.2  3.4
29   4.7  3.2
..   ...  ...
120  6.9  3.2
121  5.6  2.8
122  7.7  2.8
123  6.3  2.7
124  6.7  3.3
125  7.2  3.2
126  6.2  2.8
127  6.1  3.0
128  6.4  2.8
129  7.2  3.0
130  7.4  2.8
131  7.9  3.8
132  6.4  2.8
133  6.3  2.8
134  6.1  2.6
135  7.7  3.0
136  6.3  3.4
137  6.4  3.1
138  6.0  3.0
139  6.9  3.1
140  6.7  3.1
141  6.9  3.1
142  5.8  2.7
143  6.8  3.2
144  6.7  3.3
145  6.7  3.0
146  6.3  2.5
147  6.5  3.0
148  6.2  3.4
149  5.9  3.0

[150 rows x 2 columns]

In [4]:
k=3  
n=d1.shape[0]
c=d1.shape[1]

In [5]:
cr=d1.sample(3)
d1=np.array(d1,dtype=float)
cr=np.array(cr,dtype=float)

In [6]:
cr

array([[6.9, 3.1],
       [6.9, 3.1],
       [5.6, 2.9]])

In [7]:
c1 = []
c2 = []
c3 = []

In [8]:
def distance(cr,d1):
    a=np.empty([d1.shape[0],k])
    for i in range(cr.shape[0]):
        for j in range(d1.shape[0]):
            d=np.sum(np.square(cr[i]-d1[j]))
            a[j][i]=d
    return a

In [9]:
dist = distance(cr,d1)
dist

array([[3.4 , 3.4 , 0.61],
       [4.01, 4.01, 0.5 ],
       [4.85, 4.85, 0.9 ],
       [5.29, 5.29, 1.04],
       [3.86, 3.86, 0.85],
       [2.89, 2.89, 1.04],
       [5.38, 5.38, 1.25],
       [3.7 , 3.7 , 0.61],
       [6.29, 6.29, 1.44],
       [4.  , 4.  , 0.53],
       [2.61, 2.61, 0.68],
       [4.5 , 4.5 , 0.89],
       [4.42, 4.42, 0.65],
       [6.77, 6.77, 1.7 ],
       [2.02, 2.02, 1.25],
       [3.13, 3.13, 2.26],
       [2.89, 2.89, 1.04],
       [3.4 , 3.4 , 0.61],
       [1.93, 1.93, 0.82],
       [3.73, 3.73, 1.06],
       [2.34, 2.34, 0.29],
       [3.6 , 3.6 , 0.89],
       [5.54, 5.54, 1.49],
       [3.28, 3.28, 0.41],
       [4.5 , 4.5 , 0.89],
       [3.62, 3.62, 0.37],
       [3.7 , 3.7 , 0.61],
       [3.05, 3.05, 0.52],
       [2.98, 2.98, 0.41],
       [4.85, 4.85, 0.9 ],
       [4.41, 4.41, 0.68],
       [2.34, 2.34, 0.29],
       [3.89, 3.89, 1.6 ],
       [3.17, 3.17, 1.7 ],
       [4.  , 4.  , 0.53],
       [3.62, 3.62, 0.45],
       [2.12, 2.12, 0.37],
 

In [10]:
def asgncluster(dist):
    #mi=np.min(dist,axis=1)
    #print(mi)
    c1 = []
    c2 = []
    c3 = []
    minindx= np.argmin(dist,axis=1)
    for i in range(len(d1)):
        if minindx[i]==0:
            c1.append(d1[i])
        elif minindx[i]==1:
            c2.append(d1[i])
        else:
            c3.append(d1[i])
    return (c1,c2,c3)

In [11]:
c1,c2,c3 = asgncluster(dist)
c3

[array([5.1, 3.5]),
 array([4.9, 3. ]),
 array([4.7, 3.2]),
 array([4.6, 3.1]),
 array([5. , 3.6]),
 array([5.4, 3.9]),
 array([4.6, 3.4]),
 array([5. , 3.4]),
 array([4.4, 2.9]),
 array([4.9, 3.1]),
 array([5.4, 3.7]),
 array([4.8, 3.4]),
 array([4.8, 3. ]),
 array([4.3, 3. ]),
 array([5.8, 4. ]),
 array([5.7, 4.4]),
 array([5.4, 3.9]),
 array([5.1, 3.5]),
 array([5.7, 3.8]),
 array([5.1, 3.8]),
 array([5.4, 3.4]),
 array([5.1, 3.7]),
 array([4.6, 3.6]),
 array([5.1, 3.3]),
 array([4.8, 3.4]),
 array([5., 3.]),
 array([5. , 3.4]),
 array([5.2, 3.5]),
 array([5.2, 3.4]),
 array([4.7, 3.2]),
 array([4.8, 3.1]),
 array([5.4, 3.4]),
 array([5.2, 4.1]),
 array([5.5, 4.2]),
 array([4.9, 3.1]),
 array([5. , 3.2]),
 array([5.5, 3.5]),
 array([4.9, 3.1]),
 array([4.4, 3. ]),
 array([5.1, 3.4]),
 array([5. , 3.5]),
 array([4.5, 2.3]),
 array([4.4, 3.2]),
 array([5. , 3.5]),
 array([5.1, 3.8]),
 array([4.8, 3. ]),
 array([5.1, 3.8]),
 array([4.6, 3.2]),
 array([5.3, 3.7]),
 array([5. , 3.3]),
 a

In [12]:
def updateClusterRep(cr):
    cr = np.zeros(cr.shape)
    c1,c2,c3 = asgncluster(dist)
    for i in range(len(c1)):
        cr[0][0] += c1[i][0]
        cr[0][0] = cr[0][0]/len(c1)
        cr[0][1] += c1[i][1]
        cr[0][1] = cr[0][1]/len(c1)
    for i in range(len(c2)):
        cr[1][0] += c2[i][0]
        cr[1][0] = cr[1][0]/len(c2)
        cr[1][1] += c2[i][1]
        cr[1][1] = cr[1][1]/len(c2)
    for i in range(len(c3)):
        cr[2][0] += c3[i][0]
        cr[2][0] = cr[2][0]/len(c3)
        cr[2][1] += c3[i][1]
        cr[2][1] = cr[2][1]/len(c3)
    return cr

In [13]:
def KMeans(thres,cr,d1):
    for i in range(thres):
        dist = distance(cr,d1)
        #c1,c2,c3 = asgncluster(dist)
        cr = updateClusterRep(cr)
    return (c1,c2,c3)

In [14]:
c1F,c2F,c3F = KMeans(10,cr,d1)